### ISSUE TITLE
HDMI, miniDisplayPort

### ISSUE THREAD

**Issue by Nemec163** [vladichimescu/msi-gs65-hackintosh#1]
Hi. Great job, but i have some problems. 
HDMI and miniDisplayPort not workink. 
I've tried to connect external display - nothing happened.
Have you these ports working?

**Comment by ghost** [comment]
@Nemec163 that's because HDMI and miniDisplayPort are connected to NVIDIA gpu (you will have to use the workarounds to install nvidia on unsupported and hack the framebuffer to get displays working without acceleration - I do no recommend).
once nvidia releases the drivers 10.14 compatible, you will be able to use the dgpu config to have both intel and nvidia working.
for now, you can use an usb-c monitor or any usb-c to hdmi adapter for external monitor.

**Comment by Nemec163** [comment]
Ok, I've tested usb-c to hdmi adapter, still not working =(

This adapter have usb and ethernet ports - they working good, but nothing happened with the monitor.

**Comment by ghost** [comment]
@Nemec163 you need to drop the SSDT-DDGPU (for whatever reason that I assume is related to parent controllers in ioapic) - I will test every scenario and make this perfect if nvidia updates the drivers for os x 10.14 (or maybe I'll switch to 10.13 in near future and support that)

**Comment by ghost** [comment]
@Nemec163 I updated the structure and the files, also replaced FakeSMC with VirtualSMC and some other changes you can track in the last commit. also, based on WhateverGreen info I added how you can disable the dgpu with wegnoegpu boot arg. more than that, for now, can't do much

**Comment by ali-aati** [comment]
Hi, thank you for all your work. I am wondering does dual monitor working with High Sierra. Also, gtx 1070 graphic work. :)

**Comment by ghost** [comment]
@ali-aati I can no longer test but you should try testing what I noted in the readme:
in clover GUI, drop table SSDT-DDGPU.aml (or you can delete it in order to always keep nvidia activated)

**Comment by ali-aati** [comment]
@vladichimescu Thank you 👍
